image:
  file: .gitpod.Dockerfile
ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: open-preview
    
checkoutLocation: "web"
workspaceLocation: "."
tasks:
  - name: Web Server
    command: >
      apachectl start &&
      composer install &&
      gp open index.php
