image:
  file: .gitpod.Dockerfile
ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: open-preview
    
tasks:
  - openMode: split-right
    command: >
      apachectl start &&
      gp open public/index.php
    name: Web Server
    